### ISSUE TITLE
failed to spawn container: No such image: node:latest 

### ISSUE THREAD

**Issue by ralyodio** [semanser/codel#2]
```
2024/03/23 06:37:54 failed to spawn container: %!w(*fmt.wrapError=&{Error creating container: Error response from daemon: No such image: node:latest {0xc0007ac5e8}})
```

getting this on backend when running a task

**Comment by ralyodio** [comment]
more errors:

```
2024/03/23 06:45:19 failed to send message to channel: %!w(*fmt.wrapError=&{failed to send to the channel: connection not found for id 2 0xc00092ba00})
2024/03/23 06:45:19 failed to process terminal: %!w(*fmt.wrapError=&{failed to get connection: connection not found for id 2 0xc00092ba20})
```

**Comment by semanser** [comment]
Interesting... We have logic to check if the image is downloaded on your machine but probably it's failing somehow:

https://github.com/semanser/codel/blob/b10a9daf6a436a3d1f9e3dba783a81801d51b959/backend/executor/executor.go#L46-L57

**Comment by ralyodio** [comment]
i had to login to docker and also manually pull node:latest, but then i got these other erorrs after.

**Comment by ralyodio** [comment]
```
2024/03/23 06:45:19 failed to send message to channel: %!w(*fmt.wrapError=&{failed to send to the channel: connection not found for id 2 0xc00092ba00})
2024/03/23 06:45:19 failed to process terminal: %!w(*fmt.wrapError=&{failed to get connection: connection not found for id 2 0xc00092ba20})
```

**Comment by semanser** [comment]
I'm trying to reproduce the issue with the automatic image download but can't get to reproduce it... Here is what I'm trying:

```
> docker image rm alpine:latest
Untagged: alpine:latest
Untagged: alpine@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
Deleted: sha256:05455a08881ea9cf0e752bc48e61bbd71a34c029bb13df01e40e3e70e0d007bd
Deleted: sha256:d4fc045c9e3a848011de66f34b81f052d4f2c15a17bb196d637e526349601820
```
- Add `executor.SpawnContainer("test", "alpine:latest")` in main.go (after `executor.ProcessQueue(db)`)

<img width="980" alt="Screenshot 2024-03-23 at 14 55 20" src="https://github.com/semanser/codel/assets/4020045/e22c5642-6a1d-4bb2-997b-a1487409caf5">

- The BE is succesfully pulling the image and running it:

```
2024/03/23 14:55:32 Docker client initialized: docker-desktop
2024/03/23 14:55:32 Starting tasks processor
2024/03/23 14:55:32 Spawning container alpine:latest "test"
2024/03/23 14:55:32 Waiting for a task
2024/03/23 14:55:32 Checking if image alpine:latest exists...
2024/03/23 14:55:32 Image alpine:latest found: false
2024/03/23 14:55:32 Pulling image alpine:latest...
2024/03/23 14:55:34 Creating container test...
2024/03/23 14:55:34 connect to http://localhost:8080/playground for GraphQL playground
```

**Comment by ralyodio** [comment]
don't worry about that. i'm passed that. just add to readme that they need to 1) login to docker cli using their dockerhub creds and 2) manually pull node:latest.

These other errors are blocking me from testing the functionality of the app.

**Comment by semanser** [comment]
The manual image pulling won't work since codel is detecting the type of the docker container that is needed on the fly. For example, for a react project it will choose `node:latest`, for python - `python:latest` etc. So this issue still needs to be resolved.

About the other errors:
It seems like it's trying to send the output from the docker terminal to your frontend but it's failing to do that. I just realised that there was one more env variable missing (this time on the FE side).

Updated the readme again: https://github.com/semanser/codel?tab=readme-ov-file#frontend

I appreciate your patience and contributions.

**Comment by ralyodio** [comment]
now i get "Creating directory for hello world app..." but nothing beyond that.

**Comment by ralyodio** [comment]
still getting this error after restarting everything:
```
2024/03/23 07:15:58 failed to send message to channel: %!w(*fmt.wrapError=&{failed to send to the channel: connection not found for id 6 0xc000119960})
2024/03/23 07:15:58 failed to process terminal: %!w(*fmt.wrapError=&{failed to get connection: connection not found for id 6 0xc000119990})
```

**Comment by jondwillis** [comment]
@ralyodio are you on macOS? 

I am facing the same problem.

```
codel git:(main) docker version
Client: Docker Engine - Community
 Version:           25.0.4
 API version:       1.44
 Go version:        go1.22.1
 Git commit:        1a576c50a9
 Built:             Wed Mar  6 16:08:42 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:22 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```

**Comment by ralyodio** [comment]
no I'm on arch
