### ISSUE TITLE
openai api error

### ISSUE THREAD

**Issue by Moreh-LeeJunhyeok** [semanser/codel#45]
thank you for doing great job.
when using codel, I met 500 server error
```
2024/04/02 00:30:33 Processing command 4 of type input
2024/04/02 00:30:33 Getting next task
2024/04/02 00:30:38 Failed to get response from OpenAI error, status code: 500, message: Internal server error
```
although it does not look like codel error, [link](https://community.openai.com/t/consistent-internal-server-error-status-500-responses-for-completions-using-functions/304314) says that misusing api can be the problem.
can you investigate further?

**Comment by semanser** [comment]
Any specific steps to reproduce the issue?

**Comment by Moreh-LeeJunhyeok** [comment]
nevermind. it was a bug because I did not have access to gpt4 preview.
dont know why openai error message differs when I ran again.
closing the issue
