### ISSUE TITLE
frontend:  yarn dev triggers graphql-codegen, causing problem

### ISSUE THREAD

**Issue by billylo1** [semanser/codel#5]
Looks like it's related to prebuild and predev in package.json

Using yarn vite to start it up for now

**Comment by semanser** [comment]
Could you provide a little bit more info about the problem that you were facing? Terminal output would be helpful here.

**Comment by billylo1** [comment]
`base) billylo@pascal frontend % yarn dev
yarn run v1.22.19
$ yarn codegen
$ graphql-codegen --config codegen.yml
[Error: ENOENT: no such file or directory, open '/Users/billylo/ai/codel/frontend/codegen.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/billylo/ai/codel/frontend/codegen.yml'
}`

**Comment by semanser** [comment]
It looks like it's trying to find the codegen file but failing to do so. Make sure you didn't delete the `frontend/codegen.yml` file accidentally. Also, you can try checking if you have permissions for this file using the command:

```
➜ ls -l frontend/codegen.yml
-rw-r--r--  1 semanser  staff  349 Mar 19 14:20 frontend/codegen.yml
```

**Comment by semanser** [comment]
I am going to close this issue since we now have official Docker images that allow you to run Codel more easily. Let me know if you have any other questions!
