### ISSUE TITLE
PLEASE UPDATE THIS PROJECT TO USE LITE LLM : LLAMA 3 IS NOW OUT

### ISSUE THREAD

**Issue by RFARREY** [semanser/codel#66]
Please enable the usage of Llama 3. Litellm Api will make it easy. The project is now behind.

**Comment by semanser** [comment]
It should be possible to use Llama 3 via Ollama integration. Just set `OLLAMA_MODEL=ollama3` before running Codel.


https://ollama.com/library/llama3
